# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_job:
    name: eslint检查
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 设置node环境 Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: 安装依赖
        run: npm install

      - name: 检查
        run: npm run fix
  deploy_github_pages:
    name: 部署 GitHub pages
    runs-on: ubuntu-latest
    needs: lint_job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 设置node环境 Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      - name: 部署到 GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.GH_DEPLOY }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: deploy to github pages  # 部署时的 git 提交信息，自由填写

  deploy_tencent_cloudbase:
    name: 部署 Tencent Cloudbase
    runs-on: ubuntu-latest
    needs: lint_job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{secrets.TENCENT_SECRETID}}
          secretKey: ${{secrets.TENCENT_SECRETKEY}}
          envId: ${{secrets.TENCENT_EVNID}}

  deploy_tencent_cloudservice:

    name: 部署 Tencent CloudService
    runs-on: ubuntu-latest
    # 这里我们假定gh是dev或staging，而CloudService是prd，所以需要先在dev验证，然后人工approve之后，在发布到prd
    needs: deploy_github_pages
    environment:
      name: production
      url: http://49.234.117.123:3000/home

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENCENTCLOUD_SHH_TYLER }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.TENCENTCLOUD_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.TENCENTCLOUD_REMOTE_USER }}
          TARGET: ${{ secrets.TENCENTCLOUD_REMOTE_DIR }}
          EXCLUDE: "/node_modules/"
