# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_job:
    name: eslint检查
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # 不需要下面矩阵那么多
    #    runs-on: ${{ matrix.os }}
    #    strategy:
    #      matrix:
    #        node_version: ['10', '12']
    #        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 代码检出
      - uses: actions/checkout@v2

      - name: 设置node环境 Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 缓存依赖
        id: cache_node_modules
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: 安装依赖
        run: npm install

      - name: 检查
        run: npm run fix
  deploy:
    name: 部署
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 代码检出
      - uses: actions/checkout@v2

      - name: 设置node环境 Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      - name: 部署到 GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.DEPLOY }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: deploy to github pages  # 部署时的 git 提交信息，自由填写
    needs: lint_job
