# This is a basic workflow to help you get started with Actions

name: lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint_job:
    name: Check project eslint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # 不需要下面矩阵那么多
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        node_version: ['10', '12']
#        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # 缓存依赖
      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 安装依赖
      - name: Install
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install

      # 检查
      - name: Check
        run: npm run fix
